spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: finalproject
    url: jdbc:mysql://final-project.cugkyporweg7.us-west-2.rds.amazonaws.com:3306/fresh_food?serverTimezone=PST&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
  resources:
    static-locations: classpath:/webapp/page/
  mvc:
    view:
      prefix: /page/
      suffix: .jsp
  rabbitmq:
    host: localhost
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
      direct:
        acknowledge-mode: manual
redis:
  host: localhost
  port: 6379
  poolMaxTotal: 1000
  timeout: 100
